"""Python 3.12 opcode table (specialized/adaptive bytecodes).

Python 3.12 has ~200 opcodes including specialized variants generated by
the specializing adaptive interpreter (PEP 659). Many basic opcodes are
replaced with typed variants at runtime.

Key changes from 3.7/3.8:
  - CALL replaces CALL_FUNCTION/CALL_METHOD/CALL_FUNCTION_KW
  - BINARY_OP replaces individual BINARY_* opcodes
  - UNARY_OP not present; unary opcodes have separate entries
  - Exception handling uses PUSH_EXC_INFO/CHECK_EG_MATCH
  - RESUME at function entry instead of generator setup
  - RETURN_CONST for returning constants
  - CACHE pseudo-instructions for adaptive runtime
  - LOAD_GLOBAL split into adaptive _MODULE and _BUILTIN variants
  - JUMP_BACKWARD is relative (arg = offset backward from current)
  - FOR_ITER split into typed variants
  - COMPARE_OP split into typed variants
  - POP_JUMP_IF_FALSE/POP_JUMP_IF_TRUE (absolute jumps)
"""

# name → opcode number
opname = {
    "CACHE": 0,
    "POP_TOP": 1,
    "PUSH_NULL": 2,
    "INTERPRETER_EXIT": 3,
    "END_FOR": 4,
    "END_SEND": 5,
    "NOP": 9,
    "UNARY_NEGATIVE": 11,
    "UNARY_NOT": 12,
    "UNARY_INVERT": 15,
    "BINARY_SUBSCR": 25,
    "BINARY_SLICE": 26,
    "STORE_SLICE": 27,
    "GET_LEN": 30,
    "MATCH_MAPPING": 31,
    "MATCH_SEQUENCE": 32,
    "MATCH_KEYS": 33,
    "PUSH_EXC_INFO": 35,
    "CHECK_EXC_MATCH": 36,
    "CHECK_EG_MATCH": 37,
    "WITH_EXCEPT_START": 49,
    "GET_AITER": 50,
    "GET_ANEXT": 51,
    "BEFORE_ASYNC_WITH": 52,
    "END_ASYNC_FOR": 54,
    "CLEANUP_THROW": 55,
    "STORE_SUBSCR": 60,
    "DELETE_SUBSCR": 61,
    "GET_ITER": 68,
    "GET_YIELD_FROM_ITER": 69,
    "LOAD_BUILD_CLASS": 71,
    "LOAD_ASSERTION_ERROR": 74,
    "RETURN_GENERATOR": 75,
    "RETURN_VALUE": 83,
    "SETUP_ANNOTATIONS": 85,
    "LOAD_LOCALS": 87,
    "POP_EXCEPT": 89,
    "STORE_NAME": 90,
    "DELETE_NAME": 91,
    "UNPACK_SEQUENCE": 92,
    "FOR_ITER": 93,
    "UNPACK_EX": 94,
    "STORE_ATTR": 95,
    "DELETE_ATTR": 96,
    "STORE_GLOBAL": 97,
    "DELETE_GLOBAL": 98,
    "SWAP": 99,
    "LOAD_CONST": 100,
    "LOAD_NAME": 101,
    "BUILD_TUPLE": 102,
    "BUILD_LIST": 103,
    "BUILD_SET": 104,
    "BUILD_MAP": 105,
    "LOAD_ATTR": 106,
    "COMPARE_OP": 107,
    "IMPORT_NAME": 108,
    "IMPORT_FROM": 109,
    "JUMP_FORWARD": 110,
    "POP_JUMP_IF_FALSE": 114,
    "POP_JUMP_IF_TRUE": 115,
    "LOAD_GLOBAL": 116,
    "IS_OP": 117,
    "CONTAINS_OP": 118,
    "RERAISE": 119,
    "COPY": 120,
    "RETURN_CONST": 121,
    "BINARY_OP": 122,
    "SEND": 123,
    "LOAD_FAST": 124,
    "STORE_FAST": 125,
    "DELETE_FAST": 126,
    "LOAD_FAST_CHECK": 127,
    "POP_JUMP_IF_NOT_NONE": 128,
    "POP_JUMP_IF_NONE": 129,
    "RAISE_VARARGS": 130,
    "GET_AWAITABLE": 131,
    "MAKE_FUNCTION": 132,
    "BUILD_SLICE": 133,
    "JUMP_BACKWARD_NO_INTERRUPT": 134,
    "MAKE_CELL": 135,
    "LOAD_CLOSURE": 136,
    "LOAD_DEREF": 137,
    "STORE_DEREF": 138,
    "DELETE_DEREF": 139,
    "JUMP_BACKWARD": 140,
    "LOAD_SUPER_ATTR": 141,
    "CALL_FUNCTION_EX": 142,
    "LOAD_FAST_AND_CLEAR": 143,
    "EXTENDED_ARG": 144,
    "LIST_APPEND": 145,
    "SET_ADD": 146,
    "MAP_ADD": 147,
    "COPY_FREE_VARS": 149,
    "YIELD_VALUE": 150,
    "RESUME": 151,
    "MATCH_CLASS": 152,
    "FORMAT_VALUE": 155,
    "BUILD_CONST_KEY_MAP": 156,
    "BUILD_STRING": 157,
    "LIST_EXTEND": 162,
    "SET_UPDATE": 163,
    "DICT_MERGE": 164,
    "DICT_UPDATE": 165,
    "CALL": 171,
    "KW_NAMES": 172,
    "CALL_INTRINSIC_1": 173,
    "CALL_INTRINSIC_2": 174,
    "LOAD_FROM_DICT_OR_GLOBALS": 175,
    "LOAD_FROM_DICT_OR_DEREF": 176,
    # Specialized opcodes (adaptive interpreter)
    "BINARY_OP_ADD_FLOAT": 6,
    "BINARY_OP_ADD_INT": 7,
    "BINARY_OP_ADD_UNICODE": 8,
    "BINARY_OP_INPLACE_ADD_UNICODE": 10,
    "BINARY_OP_MULTIPLY_FLOAT": 13,
    "BINARY_OP_MULTIPLY_INT": 14,
    "BINARY_OP_SUBTRACT_FLOAT": 16,
    "BINARY_OP_SUBTRACT_INT": 18,
    "BINARY_SUBSCR_DICT": 19,
    "BINARY_SUBSCR_GETITEM": 20,
    "BINARY_SUBSCR_LIST_INT": 21,
    "BINARY_SUBSCR_TUPLE_INT": 22,
    "CALL_PY_EXACT_ARGS": 23,
    "CALL_PY_WITH_DEFAULTS": 24,
    "CALL_BOUND_METHOD_EXACT_ARGS": 28,
    "CALL_BUILTIN_CLASS": 29,
    "CALL_BUILTIN_FAST_WITH_KEYWORDS": 34,
    "CALL_METHOD_DESCRIPTOR_FAST_WITH_KEYWORDS": 38,
    "CALL_NO_KW_BUILTIN_FAST": 39,
    "CALL_NO_KW_BUILTIN_O": 40,
    "CALL_NO_KW_ISINSTANCE": 41,
    "CALL_NO_KW_LEN": 42,
    "CALL_NO_KW_LIST_APPEND": 43,
    "CALL_NO_KW_METHOD_DESCRIPTOR_FAST": 44,
    "CALL_NO_KW_METHOD_DESCRIPTOR_NOARGS": 45,
    "CALL_NO_KW_METHOD_DESCRIPTOR_O": 46,
    "CALL_NO_KW_STR_1": 47,
    "CALL_NO_KW_TUPLE_1": 48,
    "CALL_NO_KW_TYPE_1": 56,
    "COMPARE_OP_FLOAT": 57,
    "COMPARE_OP_INT": 58,
    "COMPARE_OP_STR": 59,
    "FOR_ITER_LIST": 62,
    "FOR_ITER_TUPLE": 63,
    "FOR_ITER_RANGE": 64,
    "FOR_ITER_GEN": 65,
    "LOAD_ATTR_CLASS": 70,
    "LOAD_ATTR_GETATTRIBUTE_OVERRIDDEN": 72,
    "LOAD_ATTR_INSTANCE_VALUE": 73,
    "LOAD_ATTR_MODULE": 76,
    "LOAD_ATTR_PROPERTY": 77,
    "LOAD_ATTR_SLOT": 78,
    "LOAD_ATTR_WITH_HINT": 79,
    "LOAD_ATTR_METHOD_LAZY_DICT": 80,
    "LOAD_ATTR_METHOD_NO_DICT": 81,
    "LOAD_ATTR_METHOD_WITH_VALUES": 82,
    "LOAD_CONST__LOAD_FAST": 84,
    "LOAD_FAST__LOAD_CONST": 86,
    "LOAD_FAST__LOAD_FAST": 88,
    "LOAD_GLOBAL_BUILTIN": 111,
    "LOAD_GLOBAL_MODULE": 112,
    "LOAD_SUPER_ATTR_ATTR": 66,
    "LOAD_SUPER_ATTR_METHOD": 67,
    "STORE_ATTR_INSTANCE_VALUE": 113,
    "STORE_ATTR_SLOT": 148,
    "STORE_ATTR_WITH_HINT": 153,
    "STORE_FAST__LOAD_FAST": 154,
    "STORE_FAST__STORE_FAST": 158,
    "STORE_SUBSCR_DICT": 159,
    "STORE_SUBSCR_LIST_INT": 160,
    "UNPACK_SEQUENCE_LIST": 161,
    "UNPACK_SEQUENCE_TUPLE": 166,
    "UNPACK_SEQUENCE_TWO_TUPLE": 167,
    "SEND_GEN": 168,
    # Setup opcodes (for the parser/interpreter)
    "SETUP_FINALLY": 256,
    "SETUP_CLEANUP": 257,
    "SETUP_WITH": 258,
    "POP_BLOCK": 259,
    "JUMP": 260,
    "JUMP_NO_INTERRUPT": 261,
    "LOAD_METHOD": 262,
    "LOAD_SUPER_METHOD": 263,
    "LOAD_ZERO_SUPER_METHOD": 264,
    "LOAD_ZERO_SUPER_ATTR": 265,
    "STORE_FAST_MAYBE_NULL": 266,
}

# opcode number → name
opcode = {v: k for k, v in opname.items()}

# Specialized opcodes that map back to generic ones
_SPECIALIZED_MAP = {
    6: "BINARY_OP",      # BINARY_OP_ADD_FLOAT
    7: "BINARY_OP",      # BINARY_OP_ADD_INT
    8: "BINARY_OP",      # BINARY_OP_ADD_UNICODE
    10: "BINARY_OP",     # BINARY_OP_INPLACE_ADD_UNICODE
    13: "BINARY_OP",     # BINARY_OP_MULTIPLY_FLOAT
    14: "BINARY_OP",     # BINARY_OP_MULTIPLY_INT
    16: "BINARY_OP",     # BINARY_OP_SUBTRACT_FLOAT
    18: "BINARY_OP",     # BINARY_OP_SUBTRACT_INT
    19: "BINARY_SUBSCR", # BINARY_SUBSCR_DICT
    20: "BINARY_SUBSCR", # BINARY_SUBSCR_GETITEM
    21: "BINARY_SUBSCR", # BINARY_SUBSCR_LIST_INT
    22: "BINARY_SUBSCR", # BINARY_SUBSCR_TUPLE_INT
    23: "CALL",          # CALL_PY_EXACT_ARGS
    24: "CALL",          # CALL_PY_WITH_DEFAULTS
    28: "CALL",          # CALL_BOUND_METHOD_EXACT_ARGS
    29: "CALL",          # CALL_BUILTIN_CLASS
    34: "CALL",          # CALL_BUILTIN_FAST_WITH_KEYWORDS
    38: "CALL",          # CALL_METHOD_DESCRIPTOR_FAST_WITH_KEYWORDS
    39: "CALL",          # CALL_NO_KW_BUILTIN_FAST
    40: "CALL",          # CALL_NO_KW_BUILTIN_O
    41: "CALL",          # CALL_NO_KW_ISINSTANCE
    42: "CALL",          # CALL_NO_KW_LEN
    43: "CALL",          # CALL_NO_KW_LIST_APPEND
    44: "CALL",          # CALL_NO_KW_METHOD_DESCRIPTOR_FAST
    45: "CALL",          # CALL_NO_KW_METHOD_DESCRIPTOR_NOARGS
    46: "CALL",          # CALL_NO_KW_METHOD_DESCRIPTOR_O
    47: "CALL",          # CALL_NO_KW_STR_1
    48: "CALL",          # CALL_NO_KW_TUPLE_1
    56: "CALL",          # CALL_NO_KW_TYPE_1
    57: "COMPARE_OP",    # COMPARE_OP_FLOAT
    58: "COMPARE_OP",    # COMPARE_OP_INT
    59: "COMPARE_OP",    # COMPARE_OP_STR
    62: "FOR_ITER",      # FOR_ITER_LIST
    63: "FOR_ITER",      # FOR_ITER_TUPLE
    64: "FOR_ITER",      # FOR_ITER_RANGE
    65: "FOR_ITER",      # FOR_ITER_GEN
    66: "LOAD_SUPER_ATTR",
    67: "LOAD_SUPER_ATTR",
    70: "LOAD_ATTR",     # LOAD_ATTR_CLASS
    72: "LOAD_ATTR",
    73: "LOAD_ATTR",     # LOAD_ATTR_INSTANCE_VALUE
    76: "LOAD_ATTR",     # LOAD_ATTR_MODULE
    77: "LOAD_ATTR",
    78: "LOAD_ATTR",     # LOAD_ATTR_SLOT
    79: "LOAD_ATTR",     # LOAD_ATTR_WITH_HINT
    80: "LOAD_ATTR",
    81: "LOAD_ATTR",
    82: "LOAD_ATTR",
    84: "LOAD_CONST",
    86: "LOAD_CONST",
    88: "LOAD_FAST",
    111: "LOAD_GLOBAL",  # LOAD_GLOBAL_BUILTIN
    112: "LOAD_GLOBAL",  # LOAD_GLOBAL_MODULE
    113: "STORE_ATTR",
    148: "STORE_ATTR",   # STORE_ATTR_SLOT
    153: "STORE_ATTR",
    154: "STORE_FAST",
    158: "STORE_FAST",
    159: "STORE_SUBSCR",
    160: "STORE_SUBSCR",
    161: "UNPACK_SEQUENCE",
    166: "UNPACK_SEQUENCE",
    167: "UNPACK_SEQUENCE",
    168: "SEND",
}

# For any specialized opcode, return the generic name
def get_generic_opname(op: int) -> str:
    """Map a specialized opcode back to its generic name."""
    if op in _SPECIALIZED_MAP:
        return _SPECIALIZED_MAP[op]
    return opcode.get(op, f"<{op}>")

# HAVE_ARGUMENT = 90
HAVE_ARGUMENT = 90

# Set of opcodes that take an argument
has_arg = {op for op in opcode if op >= HAVE_ARGUMENT}

# Jump opcodes (relative): target = offset + 2 + arg
JUMP_RELATIVE = {
    opname["JUMP_FORWARD"],
    opname["SETUP_FINALLY"],
    opname["SETUP_CLEANUP"],
    opname["SETUP_WITH"],
    opname["FOR_ITER"],
    62, 63, 64, 65,  # FOR_ITER_*
}

# Jump opcodes (absolute or backward)
JUMP_ABSOLUTE_SET = {
    opname["POP_JUMP_IF_FALSE"],
    opname["POP_JUMP_IF_TRUE"],
    opname["POP_JUMP_IF_NONE"],
    opname["POP_JUMP_IF_NOT_NONE"],
    opname["JUMP"],
    opname["JUMP_NO_INTERRUPT"],
}

# Backward jumps (arg = backward offset from current)
JUMP_BACKWARD_SET = {
    opname["JUMP_BACKWARD"],
    opname["JUMP_BACKWARD_NO_INTERRUPT"],
}

# Conditional jumps
JUMP_CONDITIONAL = {
    opname["POP_JUMP_IF_FALSE"],
    opname["POP_JUMP_IF_TRUE"],
    opname["POP_JUMP_IF_NONE"],
    opname["POP_JUMP_IF_NOT_NONE"],
    opname["FOR_ITER"],
    opname["SETUP_FINALLY"],
    opname["SETUP_CLEANUP"],
    opname["SETUP_WITH"],
    opname["JUMP_BACKWARD"],
    opname["JUMP_BACKWARD_NO_INTERRUPT"],
}

JUMP_OPS = JUMP_RELATIVE | JUMP_ABSOLUTE_SET | JUMP_BACKWARD_SET

TERMINATOR_OPS = {
    opname["RETURN_VALUE"],
    opname["RETURN_CONST"],
    opname["RAISE_VARARGS"],
    opname["RERAISE"],
}


def compute_target_offset(opcode_num: int, offset: int, arg: int) -> int:
    """Compute the absolute target offset for a jump instruction."""
    if opcode_num in JUMP_RELATIVE:
        return offset + 2 + arg
    elif opcode_num in JUMP_BACKWARD_SET:
        return offset + 2 - arg
    elif opcode_num in JUMP_ABSOLUTE_SET:
        return arg
    return -1
